<?php

$this->headLink()->appendStylesheet($this->basePath() . '/css/bootstrap-datetimepicker.min.css');

$this->headScript()
	->appendFile($this->basePath() . '/js/moment.min.js')
	->appendFile($this->basePath() . '/js/bootstrap-datetimepicker.min.js');

$title = 'Edit User';
$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title) . ' - ' . $username; ?></h1>

<?php
 $form->setAttribute('action', $this->url('party/user', array('action' => 'edit', 'id' => $id)));
echo $this->form($form);
?>

<script>
$(document).ready(function(){
	$('#BirthDate').datetimepicker({
		pickTime:false,
		locale:'de',
		format:'DD.MM.YYYY'
	});
});
</script>