<?php
$this->headLink()->appendStylesheet($this->basepath() . '/css/login/login.css');

$title = 'Login';
$this->headTitle($title);

?>
<form class="form-signin" method="POST" role="form" action="<?php echo $this->url('auth', array('action' => 'login'));?>">
	<h2 class="form-signin-heading">Please sign in</h2>
	<label for="inputUsername" class="sr-only">Email address</label>
	<input name="username" type="text" id="inputUsername" class="form-control" placeholder="Username" required="true" autofocus="">
	<label for="inputPassword" class="sr-only">Password</label>
	<input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
	<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>

</form>