<?php

$this->headScript()
	->appendFile($this->basePath() . '/js/selectize.min.js')
	->appendFile($this->basePath() . '/js/moment.min.js')
	->appendFile($this->basePath() . '/js/bootstrap-datetimepicker.min.js');

$this->headLink()
	->appendStylesheet($this->basePath() . '/css/selectize.bootstrap3.css')
	->appendStylesheet($this->basePath() . '/css/bootstrap-datetimepicker.min.css');

$title = 'Edit Event';
$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title) . ' - ' . $event->title; ?></h1>

<div class="row">
	<div class="col-xs-8">
		<?php
			$form->setAttribute('action', $this->url('party/event', array('action' => 'edit', 'id' => $event->eventId)));
			echo $this->form($form);
		?>
	</div>
	<div class="col-xs-4">
		<?php
			if($event->image) {
				echo "<img class='img-responsive' src='data:image/png;base64," . $event->image . "'/>";
			} else {
				echo "<img class='img-responsive' src='http://placehold.it/300&text=no+picture+available'/>";
			}
		?>
	</div>
</div>

<script>
$(document).ready(function() {
	$('#Keywords').selectize({
		persist:false,
		create:false,
		delimiter:',',
		maxItems:null,
		preload:true,
	});
	$('#Start').datetimepicker({
		language:'de',
		format:'DD.MM.YYYY HH:mm',
		sideBySide:true
	});

	$('#End').datetimepicker({
		locale:'de',
		format:'DD.MM.YYYY HH:mm',
		sideBySide:true
	});
});
</script>

