<?php

$title = 'Administrate Events';

$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a class="btn btn-default" href="<?php echo $this->url('party/event', array('action' => 'add'));?>">Add Event</a>
</p>

<table class="table">
	<tr>
		<th>Title</th>
		<th>Start</th>
		<th>End</th>
		<th>&nbsp;</th>
	</tr>
 <?php foreach ($events as $event) : ?>
	 <tr>
		<td><?php echo $this->escapeHtml($event->title);?></td>
		<td><?php echo $this->escapeHtml($event->start->format('d.m.Y H:i'));?></td>
		<td><?php echo $this->escapeHtml($event->end->format('d.m.Y H:i'));?></td>
		<td>
			<a class="btn btn-sm btn-primary" href="<?php echo $this->url('party/event', array('action' => 'edit','id' => $event->eventId));?>">Edit</a>
			<a class="btn btn-sm btn-danger" href="<?php echo $this->url('party/event', array('action' => 'delete','id' => $event->eventId));?>">Delete</a>
		</td>
	</tr>
 <?php endforeach; ?>
</table>