<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('PartyRadar')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span	class="icon-bar"></span>
				</button>
				<a class="navbar-brand" style="padding: 13px;"
					href="<?php echo $this->url('home') ?>">PartyRadar</a>
			</div>
			<div class="collapse navbar-collapse">
				    <?php
				    	$auth = new Zend\Authentication\AuthenticationService();
				    	if($auth->hasIdentity()) {
				    		$container = $this->navigation('navigation')->getContainer();
				    		echo $this->bootstrapMenu($container)->setUlClass('nav navbar-nav')->escapeLabels(false);
				    	}
					?>
			    </div>
			<!-- /.navbar-collapse -->
		</div>
	</nav>
	<div class="container">

            <?php echo $this->content; ?>
            <hr>
		<footer> </footer>
	</div>
	<!-- /container -->
</body>
</html>
